name: Sync Project Status with Progress

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

permissions:
  issues: read
  contents: read
  pull-requests: read
  projects: write

jobs:
  update_status:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: >
      (github.event_name == 'issue_comment' && !github.event.issue.pull_request) ||
      (github.event_name == 'pull_request' && github.event.pull_request.body contains 'Closes #' || github.event.pull_request.body contains 'Fixes #' || github.event.pull_request.body contains 'Resolves #')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt

    - name: Extract Issue Number
      id: extract_issue
      uses: actions/github-script@v7
      with:
        script: |
          let issueNumber;
          if (context.eventName === 'issue_comment') {
            issueNumber = context.payload.issue.number;
          } else if (context.eventName === 'pull_request') {
            // PRの本文からIssue番号を抽出
            const body = context.payload.pull_request.body || '';
            const matches = body.match(/(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)s?\s+#(\d+)/i);
            if (matches && matches[2]) {
              issueNumber = matches[2];
            }
          }
          if (issueNumber) {
            core.exportVariable('ISSUE_NUMBER', issueNumber);
            return issueNumber;
          }
          return '';

    - name: Update Status based on Progress
      if: steps.extract_issue.outputs.result != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STATUS_FIELD: ${{ secrets.STATUS_FIELD }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
      run: |
        python .github/scripts/progress_status_sync.py
